mondai/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "questions#index"
  # get 'yaji', to: "questions#yaji" 
  resources :questions do
    resources :answers
  end
end

mondai/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

mondai/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

mondai/app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: {minimum:5}
end

mondai/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @question.answers.create(answer_params)
  end

  def destroy
  end

  private
  
  def answer_params
    
  end
end

mondai/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

mondai/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all 
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
        redirect_to @question
      else
        render 'new', status: :unprocessable_entity
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path , notice: "投稿を削除しました。"
  end

  private

  def question_params
    params.require(:question).permit(:title,:name,:content)
  end
end

mondai/app/helpers/answers_helper.rb
module AnswersHelper
end

mondai/app/helpers/application_helper.rb
module ApplicationHelper
end

mondai/app/helpers/questions_helper.rb
module QuestionsHelper
end

mondai/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mondai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mondai/app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
    <% if @question.errors.any? %>
      <div>
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div>
    <div>
      <h4>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </h4>
    </div>
    <div>
      <h4>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </h4>
    </div>
    <div>
      <h4>
        <%= f.label :content %><br>
        <%= f.text_area :content %>
      </h4>
    </div>
  </div>
  <%= f.submit "送信", disable_with: '送信中...' %>
<% end %>

mondai/app/views/questions/edit.html.erb
<h1>編集</h1>
<%= render partial: 'form' %>

<%= link_to '戻る', question_path(@question)  %>

mondai/app/views/questions/index.html.erb
<h1>質問一覧</h1>

<% if @questions.present? %>
  <h4><%= @questions.count %>件の情報が見つかりました！！</h4>
    <% @questions.each do |q| %>
      <h4>
        <%= q.id %>.
        タイトル: <%= link_to question_path(q) do %><%= q.title %><% end %>
        内容: <%= link_to question_path(q) do %><%= q.content.truncate(25, separator: '.') %><% end %>
        (質問者: <%= q.name %>)
      </h4>
    <% end %>
<% else %>
  <h4>中身が見つかりませんでした。。</h4>
<% end %>

<%= link_to '新規作成', new_question_path %>

mondai/app/views/questions/new.html.erb
<h1>質問の新規作成</h1>
  <%= render partial: 'form' %>
<p><%= link_to '戻る',questions_path %></p>

mondai/app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
  <h4>
    質問者: <%= @question.name %>さん<br>
  </h4>
    <h3><%= @question.content %></h3>
  <h3>
    <h2>回答</h2>
    <%= form_with model: [@question, @question.answers.build] do |f| %>
      <h5>
        <%= f.label :name, "名前" %><br>
        <%= f.text_field :name %>
      </h5>
      <h5>
        <%= f.label :content, "内容" %><br>
        <%= f.text_area :content %>
      </h5>
      <div>
        <%= f.submit "送信", disable_with: 'Submiting...' %>
      </div>
    <% end %>
  </h3>
<p>
  <%= link_to '編集', edit_question_path(@question) %>
  <%= link_to '戻る',questions_path %>
  <%= link_to '削除', question_path(@question), data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?' }%>
</p>